# Site settings
title: Verbal
description: Tu dosis diaria de léxico
baseurl: "docs/"
url: ""
language: es

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
